name: 'Terraform Deploy to Azure'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    name: 'Build and Deploy'
    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v2

    - name: 'Setup Terraform'
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.3'  # Consider using a newer version if compatible

    - name: 'Azure Login'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Terraform Init'
      run: terraform init

    - name: 'Terraform Validate'
      run: terraform validate

    - name: 'Terraform Plan'
      run: terraform plan

    - name: 'Terraform Apply'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: terraform apply -auto-approve
      env:
        TF_VAR_snowflake_user: ${{ secrets.SNOWFLAKE_USER }}
        TF_VAR_snowflake_password: ${{ secrets.SNOWFLAKE_PASSWORD }}
        TF_VAR_snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}

    - name: 'Deploy Azure Function'
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: azure/functions-action@v1
      with:
        app_name: ${{ env.FUNCTION_APP_NAME }}  # Ensure this is set in the env or secrets
        slot_name: 'production'
        package: './FunctionApp'  # Correct path to your function app code
        publish_profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Cleanup'
      if: always()
      run: echo "Clean up actions if necessary"
